### ISSUE TITLE
solver

### ISSUE THREAD

**Issue by BlueMelon715** [mattoverby/admm-elastic-sca#2]
What if I want to do the simulation in a different way, like the newton method rather than admm optimization?

**Comment by mattoverby** [comment]
In this case, you'll need to implement gradients and hessians for each of the energy terms, and do a minimization on f(x) + g(Dx). This also means no energy-based hard constraints.

**Comment by BlueMelon715** [comment]
Thank you for your reply.

2018-01-30 1:42 GMT+09:00 Matt Overby <notifications@github.com>:
